package com.officechores.service;

import com.officechores.model.Chore;
import org.springframework.stereotype.Service;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.List;

@Service
public class RecurrenceService {

    /**
     * Returns the next N occurrence dates for a chore, starting on or after fromDate.
     */
    public List<LocalDate> getNextOccurrences(Chore chore, LocalDate fromDate, int count) {
        return switch (chore.getRecurrenceType()) {
            case NONE -> List.of(fromDate);
            case DAILY -> getDailyOccurrences(fromDate, count);
            case WEEKLY -> getWeeklyOccurrences(chore, fromDate, count);
            case MONTHLY -> getMonthlyOccurrences(chore, fromDate, count);
        };
    }

    /**
     * Returns all occurrence dates for a chore between fromDate and toDate (inclusive).
     */
    public List<LocalDate> getOccurrencesBetween(Chore chore, LocalDate fromDate, LocalDate toDate) {
        List<LocalDate> result = new ArrayList<>();
        if (chore.getRecurrenceType() == com.officechores.model.RecurrenceType.NONE) {
            return result; // One-off chores are not generated by the scheduler
        }
        LocalDate current = findFirstOccurrenceOnOrAfter(chore, fromDate);
        while (current != null && !current.isAfter(toDate)) {
            result.add(current);
            current = findNextOccurrenceAfter(chore, current);
        }
        return result;
    }

    private List<LocalDate> getDailyOccurrences(LocalDate fromDate, int count) {
        List<LocalDate> dates = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            dates.add(fromDate.plusDays(i));
        }
        return dates;
    }

    private List<LocalDate> getWeeklyOccurrences(Chore chore, LocalDate fromDate, int count) {
        List<LocalDate> dates = new ArrayList<>();
        int targetDow = chore.getRecurrenceDayOfWeek() != null ? chore.getRecurrenceDayOfWeek() : 1;
        DayOfWeek targetDay = DayOfWeek.of(targetDow);
        LocalDate next = fromDate;
        while (!next.getDayOfWeek().equals(targetDay)) {
            next = next.plusDays(1);
        }
        for (int i = 0; i < count; i++) {
            dates.add(next);
            next = next.plusWeeks(1);
        }
        return dates;
    }

    private List<LocalDate> getMonthlyOccurrences(Chore chore, LocalDate fromDate, int count) {
        List<LocalDate> dates = new ArrayList<>();
        int targetDay = chore.getRecurrenceDayOfMonth() != null ? chore.getRecurrenceDayOfMonth() : 1;
        LocalDate candidate = getMonthlyDate(fromDate.getYear(), fromDate.getMonthValue(), targetDay);
        if (candidate.isBefore(fromDate)) {
            LocalDate nextMonth = fromDate.plusMonths(1);
            candidate = getMonthlyDate(nextMonth.getYear(), nextMonth.getMonthValue(), targetDay);
        }
        for (int i = 0; i < count; i++) {
            dates.add(candidate);
            LocalDate next = candidate.plusMonths(1);
            candidate = getMonthlyDate(next.getYear(), next.getMonthValue(), targetDay);
        }
        return dates;
    }

    private LocalDate getMonthlyDate(int year, int month, int day) {
        int maxDay = YearMonth.of(year, month).lengthOfMonth();
        return LocalDate.of(year, month, Math.min(day, maxDay));
    }

    private LocalDate findFirstOccurrenceOnOrAfter(Chore chore, LocalDate fromDate) {
        return switch (chore.getRecurrenceType()) {
            case DAILY -> fromDate;
            case WEEKLY -> {
                int targetDow = chore.getRecurrenceDayOfWeek() != null ? chore.getRecurrenceDayOfWeek() : 1;
                DayOfWeek targetDay = DayOfWeek.of(targetDow);
                LocalDate d = fromDate;
                while (!d.getDayOfWeek().equals(targetDay)) d = d.plusDays(1);
                yield d;
            }
            case MONTHLY -> {
                int targetDay = chore.getRecurrenceDayOfMonth() != null ? chore.getRecurrenceDayOfMonth() : 1;
                LocalDate candidate = getMonthlyDate(fromDate.getYear(), fromDate.getMonthValue(), targetDay);
                if (candidate.isBefore(fromDate)) {
                    LocalDate nextMonth = fromDate.plusMonths(1);
                    candidate = getMonthlyDate(nextMonth.getYear(), nextMonth.getMonthValue(), targetDay);
                }
                yield candidate;
            }
            default -> null;
        };
    }

    private LocalDate findNextOccurrenceAfter(Chore chore, LocalDate current) {
        return switch (chore.getRecurrenceType()) {
            case DAILY -> current.plusDays(1);
            case WEEKLY -> current.plusWeeks(1);
            case MONTHLY -> {
                int targetDay = chore.getRecurrenceDayOfMonth() != null ? chore.getRecurrenceDayOfMonth() : 1;
                LocalDate next = current.plusMonths(1);
                yield getMonthlyDate(next.getYear(), next.getMonthValue(), targetDay);
            }
            default -> null;
        };
    }
}
